# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/OneDrive/Study/IC2/AES-128-with-an-Instruction-Set/verifyPlatform/vivado/vivado.srcs/sources_1/bd/platform/ip/platform_axi_gpio_0_0/platform_axi_gpio_0_0.xci
# IP: The module: 'platform_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/OneDrive/Study/IC2/AES-128-with-an-Instruction-Set/verifyPlatform/vivado/vivado.srcs/sources_1/bd/platform/ip/platform_axi_gpio_0_0/platform_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/OneDrive/Study/IC2/AES-128-with-an-Instruction-Set/verifyPlatform/vivado/vivado.srcs/sources_1/bd/platform/ip/platform_axi_gpio_0_0/platform_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/OneDrive/Study/IC2/AES-128-with-an-Instruction-Set/verifyPlatform/vivado/vivado.srcs/sources_1/bd/platform/ip/platform_axi_gpio_0_0/platform_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/OneDrive/Study/IC2/AES-128-with-an-Instruction-Set/verifyPlatform/vivado/vivado.srcs/sources_1/bd/platform/ip/platform_axi_gpio_0_0/platform_axi_gpio_0_0.xci
# IP: The module: 'platform_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/OneDrive/Study/IC2/AES-128-with-an-Instruction-Set/verifyPlatform/vivado/vivado.srcs/sources_1/bd/platform/ip/platform_axi_gpio_0_0/platform_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/OneDrive/Study/IC2/AES-128-with-an-Instruction-Set/verifyPlatform/vivado/vivado.srcs/sources_1/bd/platform/ip/platform_axi_gpio_0_0/platform_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/OneDrive/Study/IC2/AES-128-with-an-Instruction-Set/verifyPlatform/vivado/vivado.srcs/sources_1/bd/platform/ip/platform_axi_gpio_0_0/platform_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
