# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/platform/platform.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform || ORIG_REF_NAME==platform} -quiet] -quiet

# IP: bd/platform/ip/platform_processing_system7_0_0/platform_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_processing_system7_0_0 || ORIG_REF_NAME==platform_processing_system7_0_0} -quiet] -quiet

# IP: bd/platform/ip/platform_axi_gpio_0_0/platform_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_axi_gpio_0_0 || ORIG_REF_NAME==platform_axi_gpio_0_0} -quiet] -quiet

# IP: bd/platform/ip/platform_clk_wiz_0_0/platform_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_clk_wiz_0_0 || ORIG_REF_NAME==platform_clk_wiz_0_0} -quiet] -quiet

# IP: bd/platform/ip/platform_aesVerifyPlatformData_0_1/platform_aesVerifyPlatformData_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_aesVerifyPlatformData_0_1 || ORIG_REF_NAME==platform_aesVerifyPlatformData_0_1} -quiet] -quiet

# IP: bd/platform/ip/platform_xbar_0/platform_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_xbar_0 || ORIG_REF_NAME==platform_xbar_0} -quiet] -quiet

# IP: bd/platform/ip/platform_ps7_0_axi_periph_0/platform_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_ps7_0_axi_periph_0 || ORIG_REF_NAME==platform_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/platform/ip/platform_rst_ps7_0_50M_0/platform_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_rst_ps7_0_50M_0 || ORIG_REF_NAME==platform_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/platform/ip/platform_aes_top_0_2/platform_aes_top_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_aes_top_0_2 || ORIG_REF_NAME==platform_aes_top_0_2} -quiet] -quiet

# IP: bd/platform/ip/platform_auto_pc_0/platform_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_auto_pc_0 || ORIG_REF_NAME==platform_auto_pc_0} -quiet] -quiet

# XDC: bd/platform/platform_ooc.xdc
