

set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN N13 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property PACKAGE_PIN M16 [get_ports uart_rx]

## Switches
#set_property IOSTANDARD LVCMOS33 [get_ports work]
#set_property IOSTANDARD LVCMOS33 [get_ports enc]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports cu_chip]
set_property IOSTANDARD LVCMOS33 [get_ports clk_chip]
set_property IOSTANDARD LVCMOS33 [get_ports id_chip]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n_chip]

#set_property PACKAGE_PIN A7 [get_ports work]
#set_property PACKAGE_PIN B7 [get_ports enc]
set_property PACKAGE_PIN A8 [get_ports rst_n]
set_property PACKAGE_PIN N11 [get_ports clk]
set_property PACKAGE_PIN T14 [get_ports cu_chip]
set_property PACKAGE_PIN T8 [get_ports clk_chip]
set_property PACKAGE_PIN T15 [get_ports id_chip]
set_property PACKAGE_PIN D3 [get_ports rst_n_chip]


set_property PACKAGE_PIN E3 [get_ports {aes_rx[8]}]
set_property PACKAGE_PIN E2 [get_ports {aes_rx[7]}]
set_property PACKAGE_PIN C1 [get_ports {aes_rx[6]}]
set_property PACKAGE_PIN B2 [get_ports {aes_rx[5]}]
set_property PACKAGE_PIN C3 [get_ports {aes_rx[4]}]
set_property PACKAGE_PIN D4 [get_ports {aes_rx[3]}]
set_property PACKAGE_PIN B4 [get_ports {aes_rx[2]}]
set_property PACKAGE_PIN A5 [get_ports {aes_rx[1]}]
set_property PACKAGE_PIN D6 [get_ports {aes_rx[0]}]

set_property PACKAGE_PIN R8 [get_ports {aes_tx[8]}]
set_property PACKAGE_PIN R10 [get_ports {aes_tx[7]}]
set_property PACKAGE_PIN R11 [get_ports {aes_tx[6]}]
set_property PACKAGE_PIN P9 [get_ports {aes_tx[5]}]
set_property PACKAGE_PIN P11 [get_ports {aes_tx[4]}]
set_property PACKAGE_PIN K13 [get_ports {aes_tx[3]}]
set_property PACKAGE_PIN P13 [get_ports {aes_tx[2]}]
set_property PACKAGE_PIN R12 [get_ports {aes_tx[1]}]
set_property PACKAGE_PIN R13 [get_ports {aes_tx[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {aes_rx[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_rx[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_rx[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_rx[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_rx[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_rx[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_rx[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_rx[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_rx[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_tx[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_tx[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_tx[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_tx[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_tx[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_tx[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_tx[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_tx[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aes_tx[0]}]

##led
#set_property PACKAGE_PIN B1 [get_ports {high[2]}]
#set_property PACKAGE_PIN B6 [get_ports {high[1]}]
#set_property PACKAGE_PIN B5 [get_ports {high[0]}]
#set_property PACKAGE_PIN K5 [get_ports {low[0]}]
#set_property PACKAGE_PIN E6 [get_ports {low[1]}]
#set_property PACKAGE_PIN D1 [get_ports {low[2]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {high[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {high[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {high[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {low[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {low[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {low[0]}]
